// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurmaDwdm3.Data;

#nullable disable

namespace TurmaDwdm3.Migrations
{
    [DbContext(typeof(TurmaContext))]
    [Migration("20231213220506_migracao1")]
    partial class migracao1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TurmaDwdm3.Models.Aluno", b =>
                {
                    b.Property<int>("AlunoID")
                        .HasColumnType("int");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AlunoID");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("TurmaDwdm3.Models.Inscricao", b =>
                {
                    b.Property<int>("InscricaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscricaoID"), 1L, 1);

                    b.Property<int>("AlunoID")
                        .HasColumnType("int");

                    b.Property<int>("UcurricularID")
                        .HasColumnType("int");

                    b.HasKey("InscricaoID");

                    b.HasIndex("AlunoID");

                    b.HasIndex("UcurricularID");

                    b.ToTable("Inscricao");
                });

            modelBuilder.Entity("TurmaDwdm3.Models.Ucurricular", b =>
                {
                    b.Property<int>("UcurricularID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UcurricularID"), 1L, 1);

                    b.Property<string>("NomeUc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Nrcreditos")
                        .HasColumnType("int");

                    b.HasKey("UcurricularID");

                    b.ToTable("Ucurricular");
                });

            modelBuilder.Entity("TurmaDwdm3.Models.Inscricao", b =>
                {
                    b.HasOne("TurmaDwdm3.Models.Aluno", "Aluno")
                        .WithMany("Inscricoes")
                        .HasForeignKey("AlunoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurmaDwdm3.Models.Ucurricular", "Ucurricular")
                        .WithMany("Inscricoes")
                        .HasForeignKey("UcurricularID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Ucurricular");
                });

            modelBuilder.Entity("TurmaDwdm3.Models.Aluno", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("TurmaDwdm3.Models.Ucurricular", b =>
                {
                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
